config {
  type: "table",
  name: "taxi_final",
  description: "taxi with geomapping",
  columns: docs.final_columns,
  bigquery: {
    partitionBy: "TIMESTAMP_TRUNC(trip_start_timestamp, MONTH)",
    clusterBy: ["company", "payment_type"]
  },
  tags : ["daily"]
}


select t.*, p.road_name from ${ref("dataform", "taxi")} t 
left join ${ref("dataform", "pickup_geo_mapping")} p 
on t.pickup_latitude = p.pickup_latitude 
and t.pickup_longitude = p.pickup_longitude
